# Generated by Django 4.2.14 on 2024-07-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_node', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Обслуживание узла учета')),
                ('automation_node', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Обслуживание узла автоматики')),
                ('heat_exchanger_cleaning', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Химическая промывка теплообменника')),
                ('heat_exchanger_disassemble', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Промывка теплообменника с разборкой')),
            ],
        ),
    ]
