# Generated by Django 3.2.25 on 2024-07-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='heat_exchanger_disassemble',
        ),
    ]
