# Generated by Django 5.0.7 on 2024-07-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_calculation_heat_exchanger_dis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_number', models.CharField(max_length=4, verbose_name='Номер')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное наименование')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('account_number', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('corr_account', models.CharField(max_length=20, verbose_name='Корр. счет')),
                ('bik', models.CharField(max_length=9, verbose_name='БИК')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Наименование банка')),
            ],
        ),
    ]
