# Generated by Django 3.2.25 on 2024-07-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='i_number',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='corr_account',
            field=models.CharField(max_length=20, verbose_name='Корр счет'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
