# Generated by Django 5.0.7 on 2024-07-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240728_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='i_number',
            field=models.CharField(default=1, max_length=5, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
