# Generated by Django 3.2.25 on 2024-07-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_subscriber_i_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='i_number',
        ),
    ]
