# Generated by Django 5.0.7 on 2024-07-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_subscriber_i_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='i_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
