# Generated by Django 5.0.7 on 2024-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_subscriber_i_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='heating_node',
            field=models.IntegerField(default=0, verbose_name='Количество узлов учета отопления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_node',
            field=models.IntegerField(default=0, verbose_name='Количество узлов учета ГВС/общих'),
            preserve_default=False,
        ),
    ]
