# Generated by Django 5.0.7 on 2024-07-29 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_subscriber_heating_node_subscriber_hws_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
