# Generated by Django 5.0.7 on 2024-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_calculation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='heating_node',
            field=models.IntegerField(default=0, verbose_name='Количество узлов учета отопления'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='hws_node',
            field=models.IntegerField(default=0, verbose_name='Количество узлов учета ГВС/общих'),
        ),
    ]
