# Generated by Django 4.2.14 on 2024-07-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_calculation_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='heating_automation_node',
            field=models.IntegerField(default=0, verbose_name='Количество узлов автоматики отопления'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_automation_node',
            field=models.IntegerField(default=0, verbose_name='Количество узлов автоматики ГВС'),
        ),
    ]
