# Generated by Django 5.0.7 on 2024-07-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_subscriber_heating_automation_node_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='heat_exchanger_cleaning',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='service_node',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='heating_node',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='hws_node',
        ),
        migrations.AddField(
            model_name='calculation',
            name='heat_exchanger_cleaning_highprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Химическая промывка теплообменника (вариант 2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculation',
            name='heat_exchanger_cleaning_lowprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Химическая промывка теплообменника (вариант 1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculation',
            name='service_4_year_node',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Обслуживание узла учета до 4-х лет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculation',
            name='service_node_modem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Обслуживание узла учета с автоматической передачей данных'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculation',
            name='service_node_no_modem',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Обслуживание узла учета без автоматической передачи данных'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='heating_4_year_node',
            field=models.IntegerField(default=0, verbose_name='Количество узлов отопления до 4-х лет'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='heating_node_modem',
            field=models.IntegerField(default=0, verbose_name='Количество узлов учета отопления с автоматической передачей данных'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='heating_node_no_modem',
            field=models.IntegerField(default=0, verbose_name='Количество узлов учета отопления без автоматической передачи данных'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_4_year_node',
            field=models.IntegerField(default=0, verbose_name='Количество узлов ГВС/общих до 4-х лет'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_node_modem',
            field=models.IntegerField(default=0, verbose_name='Количество узлов учета ГВС/общих с автоматической передачей данных'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_node_no_modem',
            field=models.IntegerField(default=0, verbose_name='Количество узлов учета ГВС/общих без автоматической передачи данных'),
        ),
    ]
