# Generated by Django 5.0.7 on 2024-07-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_calculation_heat_exchanger_cleaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='verification',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Поверка прибора'),
            preserve_default=False,
        ),
    ]
