# Generated by Django 5.0.7 on 2024-07-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_calculation_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculation',
            options={'ordering': ['-date_created']},
        ),
    ]
