# Generated by Django 5.0.7 on 2024-07-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_calculation_automation_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='automation_node',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Обслуживание узла автоматики'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='service_4_year_node',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Обслуживание узла учета до 4-х лет'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='service_node_modem',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Обслуживание узла учета с автоматической передачей данных'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='service_node_no_modem',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Обслуживание узла учета без автоматической передачи данных'),
        ),
    ]
