# Generated by Django 5.0.7 on 2024-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_subscriber_kpp_subscriber_l_number_subscriber_ogrn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='service_4_year_node',
            new_name='service_four_year_node',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='heating_4_year_node',
            new_name='heating_four_year_node',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='hws_4_year_node',
            new_name='hws_four_year_node',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='i_number',
            field=models.IntegerField(verbose_name='Номер договора'),
        ),
    ]
