# Generated by Django 4.2.14 on 2024-09-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_subscriber_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='address',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='house',
            field=models.CharField(default=0, max_length=6, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='post_index',
            field=models.CharField(default=0, max_length=6, verbose_name='Почтовый индекс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='street',
            field=models.CharField(default=0, max_length=100, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
