# Generated by Django 4.2.14 on 2024-09-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_subscriber_address_subscriber_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='total_contracts',
            field=models.IntegerField(default=0),
        ),
    ]
