# Generated by Django 4.2.14 on 2024-12-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_subscriber_total_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='total_contract_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма всех договоров'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
