# Generated by Django 4.2.14 on 2024-12-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_subscriber_total_contract_sum_alter_calculation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='contract_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Сумма договора'),
        ),
    ]
