# Generated by Django 4.2.14 on 2024-12-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_subscriber_contract_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='contract_sum',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма договора'),
        ),
    ]
