# Generated by Django 4.2.14 on 2024-12-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_subscriber_contract_sum_subscriber_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='heating_node_modem_checkbox',
            field=models.BooleanField(default=False, verbose_name='Чекбокс для узлов отопления с автоматической передачей данных'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='heating_node_no_modem_checkbox',
            field=models.BooleanField(default=False, verbose_name='Чекбокс для узлов отопления без автоматической передачи данных'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_node_modem_checkbox',
            field=models.BooleanField(default=False, verbose_name='Чекбокс для узлов ГВС/общих с автоматической передачей данных'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_node_no_modem_checkbox',
            field=models.BooleanField(default=False, verbose_name='Чекбокс для узлов ГВС/общих без автоматической передачи данных'),
        ),
    ]
