# Generated by Django 4.2.14 on 2024-12-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_subscriber_heating_node_modem_checkbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='heatind_automation_node_checkbox',
            field=models.BooleanField(default=False, verbose_name='Чекбокс для автоматики отопления'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_automation_node_checkbox',
            field=models.BooleanField(default=False, verbose_name='Чекбокс для автоматики ГВС'),
        ),
    ]
