# Generated by Django 4.2.14 on 2025-01-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_subscriber_heatind_automation_node_checkbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='heatind_automation_node_checkbox',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='heating_automation_node_checkbox',
            field=models.BooleanField(default=False, verbose_name='Скидка для автоматики отопления'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='heating_node_modem_checkbox',
            field=models.BooleanField(default=False, verbose_name='Скидка для узлов отопления с автоматической передачей данных'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='heating_node_no_modem_checkbox',
            field=models.BooleanField(default=False, verbose_name='Скидка для узлов отопления без автоматической передачи данных'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='hws_automation_node_checkbox',
            field=models.BooleanField(default=False, verbose_name='Скидка для автоматики ГВС'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='hws_node_modem_checkbox',
            field=models.BooleanField(default=False, verbose_name='Скидка для узлов ГВС/общих с автоматической передачей данных'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='hws_node_no_modem_checkbox',
            field=models.BooleanField(default=False, verbose_name='Скидка для узлов ГВС/общих без автоматической передачи данных'),
        ),
    ]
