# Generated by Django 4.2.14 on 2025-01-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_subscriber_heatind_automation_node_checkbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='heating_automation_node_checkbox',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='heating_node_modem_checkbox',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='heating_node_no_modem_checkbox',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='hws_automation_node_checkbox',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='hws_node_modem_checkbox',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='hws_node_no_modem_checkbox',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='heating_automation_node_discount',
            field=models.IntegerField(default=0, verbose_name='Количество автоматики отопления со скидкой'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='heating_node_modem_discount',
            field=models.IntegerField(default=0, verbose_name='Количество узлов отопления с автоматической передачей данных со скидкой'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='heating_node_no_modem_discount',
            field=models.IntegerField(default=0, verbose_name='Количество узлов отопления без автоматической передачи данных со скидкой'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_automation_node_discount',
            field=models.IntegerField(default=0, verbose_name='Количество узлов автоматики ГВС со скидкой'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_node_modem_discount',
            field=models.IntegerField(default=0, verbose_name='Количество узлов ГВС/общих с автоматической передачей данных со скодкой'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hws_node_no_modem_discount',
            field=models.IntegerField(default=0, verbose_name='Количество узлов ГВС/общих без автоматической передачи данных со скидкой'),
        ),
    ]
