# Generated by Django 4.2.14 on 2025-01-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_subscriber_heating_automation_node_checkbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='heat_exchanger_cleaning_highprice',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='heat_exchanger_cleaning_lowprice',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='heat_exchanger_dis',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='verification',
        ),
    ]
