# Generated by Django 4.2.14 on 2025-02-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_calculation_heat_exchanger_cleaning_highprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='myapp.calculation', verbose_name='Калькуляция'),
        ),
    ]
