# Generated by Django 4.2.14 on 2025-02-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_subscriber_calculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='calculation',
        ),
    ]
