# Generated by Django 4.2.14 on 2025-02-03 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_subscriber_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='myapp.calculation', verbose_name='Калькуляция'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
