# Generated by Django 4.2.14 on 2025-02-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_subscriber_calculation_alter_calculation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='calculation',
        ),
        migrations.AlterField(
            model_name='calculation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
